<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
	<!ELEMENT root (security,data)>
	<!ATTLIST root id ID #REQUIRED>

	<!ELEMENT security (pin,question,answer)>
	<!ATTLIST security id ID #REQUIRED>

	<!ELEMENT data (total,category+)>
	<!ATTLIST data id ID #REQUIRED>

	<!ELEMENT pin (#PCDATA)>
	<!ATTLIST pin id ID #REQUIRED>

	<!ELEMENT question (#PCDATA)>
	<!ATTLIST question id ID #REQUIRED>

	<!ELEMENT answer (#PCDATA)>
	<!ATTLIST answer id ID #REQUIRED>

	<!ELEMENT category (label,total,year*)>
	<!ATTLIST category id ID #REQUIRED>

	<!ELEMENT label (#PCDATA)>
	<!ATTLIST label id ID #REQUIRED>

	<!ELEMENT year (total,month+)>
	<!ATTLIST year id ID #REQUIRED>

	<!ELEMENT month (total,day+)>
	<!ATTLIST month id ID #REQUIRED>

	<!ELEMENT day (total,entry+)>
	<!ATTLIST day id ID #REQUIRED>

	<!ELEMENT entry (amount,description)>
	<!ATTLIST entry id ID #REQUIRED>

	<!ELEMENT amount (#PCDATA)>
	<!ATTLIST amount id ID #REQUIRED>

	<!ELEMENT description (#PCDATA)>
	<!ATTLIST description id ID #REQUIRED>

	<!ELEMENT total (#PCDATA)>
	<!ATTLIST total id ID #REQUIRED>
	]>
<root id="r">
	<security id="s">
		<pin id="p">1234</pin>
		<question id="q">What city were you born in?</question>
		<answer id="a">Seattle</answer>
	</security>
	<data id="d">
		<total id="t">133.00</total>
		<category id="c-1">
			<label id="c-1-l">Food</label>
			<total id="c-1-t">7.00</total>
			<year id="c-1-2020">
				<total id="c-1-2020-t">7.00</total>
				<month id="c-1-2020-02">
					<total id="c-1-2020-02-t">7.00</total>
					<day id="c-1-2020-02-13">
						<total id="c-1-2020-02-13-t">7.00</total>
						<entry id="c-1-2020-02-13-1">
							<amount id="c-1-2020-02-13-1-a">5.00</amount>
							<description id="c-1-2020-02-13-1-d">Starbucks Venti Mocha</description>
						</entry>
						<entry id="c-1-2020-02-13-2">
							<amount id="c-1-2020-02-13-2-a">2.00</amount>
							<description id="c-1-2020-02-13-2-d"></description>
						</entry>
					</day>
				</month>
			</year>
		</category>
		<category id="c-2">
			<label id="c-2-l">Entertainment</label>
			<total id="c-2-t">34.00</total>
			<year id="c-2-2019">
				<total id="c-2-2019-t">34.00</total>
				<month id="c-2-2019-02">
					<total id="c-2-2019-02-t">15.00</total>
					<day id="c-2-2019-02-16">
						<total id="c-2-2019-02-16-t">15.00</total>
						<entry id="c-2-2019-02-16-1">
							<amount id="c-2-2019-02-16-1-a">15.00</amount>
							<description id="c-2-2019-02-16-1-d">Star Wars Movie Night</description>
						</entry>
					</day>
				</month>
				<month id="c-2-2019-01">
					<total id="c-2-2019-01-t">19.00</total>
					<day id="c-2-2019-01-28">
						<total id="c-2-2019-01-28-t">8.00</total>
						<entry id="c-2-2019-01-28-1">
							<amount id="c-2-2019-01-28-1-a">8.00</amount>
							<description id="c-2-2019-01-28-1-d"></description>
						</entry>
					</day>
					<day id="c-2-2019-01-10">
						<total id="c-2-2019-01-10-t">11.00</total>
						<entry id="c-2-2019-01-10-1">
							<amount id="c-2-2019-01-10-1-a">11.00</amount>
							<description id="c-2-2019-01-10-1-d">Mini Golf</description>
						</entry>
					</day>
				</month>
			</year>
		</category>
		<category id="c-3">
			<label id="c-3-l">Transportation</label>
			<total id="c-3-t">92.00</total>
			<year id="c-3-2019">
				<total id="c-3-2019-t">47.00</total>
				<month id="c-3-2019-01">
					<total id="c-3-2019-01-t">47.00</total>
					<day id="c-3-2019-01-16">
						<total id="c-3-2019-01-16-t">47.00</total>
						<entry id="c-3-2019-01-16-1">
							<amount id="c-3-2019-01-16-1-a">47.00</amount>
							<description id="c-3-2019-01-16-1-d"></description>
						</entry>
					</day>
				</month>
			</year>
			<year id="c-3-2018">
				<total id="c-3-2018-t">90.00</total>
				<month id="c-3-2018-12">
					<total id="c-3-2018-12-t">90.00</total>
					<day id="c-3-2018-12-03">
						<total id="c-3-2018-12-03-t">90.00</total>
						<entry id="c-3-2018-12-03-1">
							<amount id="c-3-2018-12-03-1-a">45.00</amount>
							<description id="c-3-2018-12-03-1-d">Gas</description>
						</entry>
						<entry id="c-3-2018-12-03-2">
							<amount id="c-3-2018-12-03-2-a">45.00</amount>
							<description id="c-3-2018-12-03-2-d">Gas</description>
						</entry>
					</day>
				</month>
			</year>
		</category>
	</data>
</root>
